sudo: required

#language: csharp
#mono: none
#dotnet: 2.0.0
language: python
python:
  - "3.6" 
dist: trusty

#safelist
branches:
  only:
  - master
  - develop

addons:
  sonarcloud:
    organization: "bevrand"
    token:
      secure: "$SONAR_TOKEN"

notifications:
  slack: bevrand:JiQ1Phpayqdnsbi2pdYvdqhJ

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker --version
  - docker-compose build
  - docker images
  - docker-compose up -d
  - docker ps -a

script:
  - sonar-scanner
 # - cd ./bevrand.testsuite
 # - pwd
 # - dotnet test
  - cd ./deployment
  - ls
  - python3 validate_backend_test_results.py

after_success:
 # - cd ../deployment
 # - pwd
 # - sh ./push_images.sh
 # - sh ./init_terraform.sh
 # - cd ./terraform_scripts
 # - pwd
 # - sh ../run_terraform.sh
