version: "2"
services:

  randomizerapi:
    container_name: randomizerapi
    build: ./bevrand.randomizerapi
    ports:
       - 4560:5000 # expose ports - HOST:CONTAINER
    depends_on:
       - mongoapi
       - redis
    links:
       - mongoapi
       - redis
    environment:
       - CONNECTION=redis
       - REQURL=http://mongoapi:5000/
   
  mongoapi:
    container_name: mongoapi
    build: ./bevrand.mongoapi
    ports:
       - 4550:5000  # expose ports - HOST:CONTAINER
    depends_on:
       - dockermongo
    links:
       - dockermongo
    environment:
       - APP_SETTINGS=Production
       - MONGO_URL=mongodb://dockermongo:27017
  
  nodefrontend:
    container_name: nodefrontend
    build: ./bevrand.nodefrontend
    ports:
      - 4540:4540
    depends_on:
      - randomizerapi
      - mongoapi
    environment:
      - NODE_ENV=production
    links:
      - randomizerapi
      - mongoapi

  redis:
    container_name: redis
    image: redis
    ports: #6379
      - 6379:6379

  dockermongo:
    container_name: dockermongo
    image: mongo
    ports:
       - 27017:27017

  mongoseeder:
    container_name: mongoseeder
    build: ./bevrand.mongoseeder
    depends_on:
       - dockermongo
    links:
       - dockermongo
