version: "2"
services:

  redis:
    container_name: redis
    image: redis
    ports: #6379
      - 6379:6379

  dockermongo:
    container_name: dockermongo
    image: mongo
    ports:
       - 27017:27017

  dockergres:
     container_name: dockergres
     build: ./bevrand.mongoseeder/db
     ports:
       - 5432:5432
     environment:
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_USER=postgres

  authenticationapi:
    container_name: authenticationapi
    build: ./bevrand.authenticationapi/bevrand.authenticationapi
    ports:
      - 4570:5000
    depends_on:
      - dockergres
    links:
      - dockergres
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"

  randomizerapi:
    container_name: randomizerapi
    build: ./bevrand.randomizerapi
    ports:
       - 4560:5000 # expose ports - HOST:CONTAINER
    depends_on:
       - mongoapi
       - redis
    links:
       - mongoapi
       - redis
    environment:
       - APP_SETTINGS=production
       - REDIS_URL=redis

  mongoapi:
    container_name: mongoapi
    build: ./bevrand.mongoapi
    ports:
       - 4550:5000  # expose ports - HOST:CONTAINER
    depends_on:
       - dockermongo
    links:
       - dockermongo
    environment:
       - APP_SETTINGS=production
       - MONGO_URL=mongodb://dockermongo:27017

  nodefrontend:
    container_name: nodefrontend
    build: ./bevrand.frontend
    ports:
      - 4540:5000
    depends_on:
      - randomizerapi
      - mongoapi
      - authenticationapi
    environment:
      - NODE_ENV=production
    links:
      - randomizerapi
      - mongoapi
      - authenticationapi

  mongoseeder:
    container_name: mongoseeder
    build: ./bevrand.mongoseeder
    depends_on:
       - dockermongo
       - dockergres
    links:
       - dockermongo
       - dockergres

  selenium-hub:
    image: selenium/hub
    ports:
      - 4444:4444
    environment:
      - GRID_TIMEOUT=10

  chrome:
    image: selenium/node-chrome
    links:
      - selenium-hub:hub
    environment:
      - HUB_HOST=selenium-hub
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952a

  firefox:
    image: selenium/node-firefox
    environment:
      - HUB_HOST=selenium-hub
    links:
      - selenium-hub:hub
