version: "2"
services:

  redis:
    container_name: redis
    image: redis
    ports: #6379
      - 6379:6379

  dockermongo:
    container_name: dockermongo
    image: mongo:3.6
    ports:
       - 27017:27017

  dockergres:
     container_name: dockergres
     build: ./bevrand.dataseeder/db
     ports:
       - 5434:5432
     environment:
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_USER=postgres

  authenticationapi:
    container_name: authenticationapi
    build: ./bevrand.authenticationapi/bevrand.authenticationapi
    ports:
      - 4570:5000
    depends_on:
      - dockergres
    links:
      - dockergres
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"

  randomizerapi:
    container_name: randomizerapi
    build: ./bevrand.randomizerapi
    ports:
       - 4560:5000 # expose ports - HOST:CONTAINER
    depends_on:
       - playlistapi
    links:
       - playlistapi
       - highscoreapi
    environment:
       - APP_SETTINGS=Production
       - HIGHSCORE_API=http://highscoreapi:5000/api/v1/

  playlistapi:
    container_name: playlistapi
    build: ./bevrand.playlistapi
    ports:
       - 4550:5000  # expose ports - HOST:CONTAINER
    depends_on:
       - dockermongo
    links:
       - dockermongo
    environment:
       - APP_SETTINGS=Coverage
       - MONGO_URL=mongodb://dockermongo:27017/admin

  proxyapi:
    container_name: proxyapi
    build: ./bevrand.proxyapi
    ports:
      - 4540:5000
    depends_on:
      - randomizerapi
      - playlistapi
      - authenticationapi
    environment:
      - NODE_ENV=development
    links:
      - randomizerapi
      - playlistapi
      - authenticationapi

  highscoreapi:
    container_name: highscoreapi
    build: ./bevrand.highscoreapi
    environment:
    - GO_ENV=docker
    - GIN_MODE=release
    depends_on:
    - redis
    links:
    - redis
    ports:
    - 4580:5000

  frontendapi:
    container_name: frontend
    build: ./bevrand.frontend
    ports:
    - 80:80
    depends_on:
    - randomizerapi
    - playlistapi
    - authenticationapi
    - proxyapi
    links:
    - proxyapi

  dataseeder:
    container_name: dataseeder
    build: ./bevrand.dataseeder
    depends_on:
       - dockermongo
       - dockergres
    links:
       - dockermongo
       - dockergres

  componenttest:
    container_name: component_tests
    build: ./bevrand.componenttests
    depends_on:
    - randomizerapi
    - playlistapi
    - authenticationapi
    - proxyapi
    - highscoreapi
    - dataseeder
    links:
    - randomizerapi
    - playlistapi
    - authenticationapi
    - proxyapi
    - highscoreapi
    environment:
    - PYTHON_ENV=Test


      