version: '3.1'

services:
  authenticationapi:
    build: ./bevrand.authenticationapi/bevrand.authenticationapi
    container_name: authenticationapi
    depends_on:
    - dockergres
    environment:
    - ConnectionStrings:PostGres=Host=dockergres;Port=5432;Database=bevrand;Uid=Jt6YiwS0D3AnTx8;Pwd=XkND32hL1ASyIj8!Js7oiYBpc;
    - ASPNETCORE_ENVIRONMENT="Production"
    ports:
    - 4570:5000
  dataseeder:
    build: ./bevrand.dataseeder
    container_name: dataseeder
    depends_on:
    - dockermongo
    - dockergres
    environment:
    - MONGO_URL=mongodb://Jt6YiwS0D3AnTx8:XkND32hL1ASyIj8!Js7oiYBpc@dockermongo:27017/admin
    links:
    - dockermongo
    - dockergres
  dockergres:
    build: ./bevrand.dataseeder/db
    container_name: dockergres
    environment:
    - POSTGRES_PASSWORD=XkND32hL1ASyIj8!Js7oiYBpc
    - POSTGRES_USER=Jt6YiwS0D3AnTx8
    ports:
    - 5434:5432
  dockermongo:
    container_name: dockermongo
    environment:
    - AWESOME_NUMBER = 42
    - MONGO_INITDB_ROOT_USERNAME=Jt6YiwS0D3AnTx8
    - MONGO_INITDB_ROOT_PASSWORD=XkND32hL1ASyIj8!Js7oiYBpc
    image: mongo:4.0
    ports:
    - 27017:27017
  dockernginx:
    build: ./deployment/nginx
    container_name: dockernginx
    depends_on:
    - proxyapi
    - multivuerse
    ports:
    - 80:5000
  highscoreapi:
    build: ./bevrand.highscoreapi
    container_name: highscoreapi
    depends_on:
    - redis
    environment:
    - GO_ENV=docker
    - GIN_MODE=release
    ports:
    - 4580:5000
  playlistapi:
    build: ./bevrand.playlistapi
    container_name: playlistapi
    depends_on:
    - dockermongo
    environment:
    - APP_SETTINGS=Production
    - MONGO_URL=mongodb://Jt6YiwS0D3AnTx8:XkND32hL1ASyIj8!Js7oiYBpc@dockermongo:27017/admin
    ports:
    - 4550:5000
  proxyapi:
    build: ./bevrand.proxyapi
    container_name: proxyapi
    depends_on:
    - randomizerapi
    - playlistapi
    - authenticationapi
    environment:
    - NODE_ENV=development
    ports:
    - 4540:5000
  randomizerapi:
    build: ./bevrand.randomizerapi
    container_name: randomizerapi
    environment:
    - APP_SETTINGS=Production
    - HIGHSCORE_API=http://highscoreapi:5000/api/v1/
    ports:
    - 4560:5000
  redis:
    container_name: redis
    image: redis
    ports:
    - 6379:6379
  multivuerse:
    build: ./bevrand.multivuerse
    container_name: multivuerse
    depends_on:
    - proxyapi
    environment:
    - NODE_ENV=production
    ports:
    - 3001:3000
