apiVersion: v1
kind: Service
metadata:
  name: dockergres
  labels:
    app.kubernetes.io/name: {{ include "bevrand.name" . }}-dockergres
    helm.sh/chart: {{ include "bevrand.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app.kubernetes.io/name: {{ include "bevrand.name" . }}-dockergres
    app.kubernetes.io/instance: {{ .Release.Name }}