apiVersion: v1
kind: Service
metadata:
  name: {{ include "bevrand.name" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "bevrand.name" . }}-frontend
    helm.sh/chart: {{ include "bevrand.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app.kubernetes.io/name: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}