apiVersion: v1
kind: Service
metadata:
  name: playlistapi
  labels:
    app.kubernetes.io/name: {{ include "bevrand.name" . }}-playlistapi
    helm.sh/chart: {{ include "bevrand.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    app.kubernetes.io/name: {{ include "bevrand.name" . }}-playlistapi
    app.kubernetes.io/instance: {{ .Release.Name }}
