apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app.kubernetes.io/name: {{ include "bevrand.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}