#%RAML 1.0
title: Playlist Api
version: v1
baseUri: http://127.0.0.1:5000
description: Part of the BeverageRandomizer. This api serves playlists from Mongo


/api/frontpages:
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              id: string
              user: string
              list: string
              beverages: array
              displayName: string
              imageUrl: string
            example:
              {
              "id": "0a8bc561-e077-4994-811b-cd73e85aaee3",
              "user": "frontpage",
              "list": "TGIF",
              "beverages": [
              "beer", "wine"
              ],
              displayName: "Thank god it's friday",
              imageUrl: "https://someimage.com/tgif"
              }
      503:
        body:
          application/json:
            type: object
            properties:
              message: string
              status_code: integer
              meta: object
