apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "art.fullname" . }}
  labels:
{{ include "art.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- if .Values.strategyType }}
  strategy:
    type: {{ .Values.strategyType }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "art.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "art.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
{{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName | quote }}
{{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.config }}
          env:
  {{- range $key, $value := .Values.config }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
  {{- end }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
