version: 2

jobs:
  build:
    machine: true
    steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     #- run: |
     #    docker login -u $DOCKER_USER -p $DOCKER_PASS
     #    docker run -d --name db company/proprietary-db:1.2.3

     # build the application image
     #- run: docker build -t company/app:$CIRCLE_BRANCH .
     - run: docker-compose --version
     - run: docker --version
     - run: docker-compose build
     - run: docker images
     - run: docker-compose up -d
     - run: docker ps -a
     # deploy the image
     #- run: docker push company/app:$CIRCLE_BRANCH
  pause_uptimerobot:
    machine: true
    steps:
     - run: "curl -X POST -H \"Cache-Control: no-cache\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"api_key=$UptimeRobotApiKey&format=json&id=780479363&status=0\" \"https://api.uptimerobot.com/v2/editMonitor\" && curl -X POST -H \"Cache-Control: no-cache\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"api_key=$UptimeRobotApiKey&format=json&id=780479359&status=0\" \"https://api.uptimerobot.com/v2/editMonitor\" && curl -X POST -H \"Cache-Control: no-cache\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"api_key=$UptimeRobotApiKey&format=json&id=780460902&status=0\" \"https://api.uptimerobot.com/v2/editMonitor\" && curl -X POST -H \"Cache-Control: no-cache\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"api_key=$UptimeRobotApiKey&format=json&id=780460904&status=0\" \"https://api.uptimerobot.com/v2/editMonitor\""
  deploy:
    machine: true
    steps:
     - checkout
     - run: "pwd && ls -lha"
     - run: "cd ./deployment"
     - run: "sh ./push_images.sh"
     - run: "sh ./init_terraform.sh"
     - run: "cd ./terraform_scripts"
     - run: "pwd && ls -lha"
     - run: "sh ../run_terraform.sh"
  resume_uptimerobot:
    machine: true
    steps:
     - run: "curl -X POST -H \"Cache-Control: no-cache\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"api_key=$UptimeRobotApiKey&format=json&id=780479363&status=1\" \"https://api.uptimerobot.com/v2/editMonitor\" && curl -X POST -H \"Cache-Control: no-cache\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"api_key=$UptimeRobotApiKey&format=json&id=780479359&status=1\" \"https://api.uptimerobot.com/v2/editMonitor\" && curl -X POST -H \"Cache-Control: no-cache\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"api_key=$UptimeRobotApiKey&format=json&id=780460902&status=1\" \"https://api.uptimerobot.com/v2/editMonitor\" && curl -X POST -H \"Cache-Control: no-cache\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"api_key=$UptimeRobotApiKey&format=json&id=780460904&status=1\" \"https://api.uptimerobot.com/v2/editMonitor\""

workflows:
  version: 2
  build_accept_deploy:
    jobs:
     - build
     #TODO Sonar-scanner
     #- acceptance_test_1:
     #    requires:
     #      - build
     - pause_uptimerobot:
         requires:
           - build
     - deploy:
         requires:
           #- acceptance_test_1
           - pause_uptimerobot
     - resume_uptimerobot:
         requires:
           - deploy
         