apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Bevrand-PROD-newdroplet.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: authenticationapi
  name: authenticationapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: authenticationapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: '"Production"'
        - name: ConnectionStrings
          value: PostGres=Host=dockergres;Port=5432;Database=bevrand;Uid=<PostGresUser>;Pwd=<PostGresPassWord>;
        image: bevrand/authenticationapi:latest
        name: authenticationapi
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
