apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: dataseeder
  name: dataseeder
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dataseeder
    spec:
      containers:
      - image: bevrand/dataseeder:latest
        name: dataseeder
        resources: {}
      restartPolicy: Always
status: {}
