apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Bevrand-PROD-newdroplet.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: dockermongo
  name: dockermongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dockermongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: <MonogPassWord>
        - name: MONGO_INITDB_ROOT_USERNAME
          value: <MongoUser>
        image: mongo:3.6.3
        name: dockermongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: dockermongo-claim0
      restartPolicy: Always
      volumes:
      - name: dockermongo-claim0
        persistentVolumeClaim:
          claimName: dockermongo-claim0
status: {}
