apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Bevrand-PROD-newdroplet.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: dockergres
  name: dockergres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dockergres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: <PostGresPass>
        - name: POSTGRES_USER
          value: <PostGresUser>
        image: postgres:latest
        name: dockergres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dockergres-claim0
      restartPolicy: Always
      volumes:
      - name: dockergres-claim0
        persistentVolumeClaim:
          claimName: dockergres-claim0
status: {}
