apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f Bevrand-PROD-newdroplet.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: nodefrontend
  name: nodefrontend
spec:
  ports:
  - name: "4540"
    port: 4540
    targetPort: 5000
  selector:
    io.kompose.service: nodefrontend
status:
  loadBalancer: {}
