apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Bevrand-PROD-newdroplet.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: nodefrontend
  name: nodefrontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nodefrontend
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        image: bevrand/nodefrontend:latest
        name: nodefrontend
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
