apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Bevrand-PROD-newdroplet.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: randomizerapi
  name: randomizerapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: randomizerapi
    spec:
      containers:
      - env:
        - name: APP_SETTINGS
          value: production
        - name: REDIS_URL
          value: redis
        image: bevrand/randomizerapi:latest
        name: randomizerapi
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
