apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f Bevrand-PROD-newdroplet.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: randomizerapi
  name: randomizerapi
spec:
  ports:
  - name: "4560"
    port: 4560
    targetPort: 5000
  selector:
    io.kompose.service: randomizerapi
status:
  loadBalancer: {}
