apiVersion: v1
kind: Deployment
metadata:
  name: randomizerapi
labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
      - env:
        - name: APP_SETTINGS
          value: production
        image: bevrand/randomizerapi:production
        name: randomizerapi
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
