version: "3"
services:

  authenticationapi:
    container_name: authenticationapi
    image: "bevrand/authenticationapi:${CIRCLE_SHA1}"
    ports:
      - 4570:5000
    depends_on:
      - dockergres
    links:
      - dockergres
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"

  randomizerapi:
    container_name: randomizerapi
    image: "bevrand/randomizerapi:${CIRCLE_SHA1}"
    ports:
       - 4560:5000 # expose ports - HOST:CONTAINER
    depends_on:
       - highscoreapi
    links:
       - highscoreapi
    environment:
       - APP_SETTINGS=Production
       - HIGHSCORE_API=http://highscoreapi:5000/api/v1/


  playlistapi:
    container_name: playlistapi
    image: "bevrand/playlistapi:${CIRCLE_SHA1}"
    ports:
       - 4550:5000  # expose ports - HOST:CONTAINER
    depends_on:
       - dockermongo
    links:
       - dockermongo
    environment:
       - APP_SETTINGS=Production
       - MONGO_URL=mongodb://dockermongo:27017

  proxyapi:
    container_name: proxyapi
    image: "bevrand/proxyapi:${CIRCLE_SHA1}"
    ports:
      - 4540:5000
    depends_on:
      - randomizerapi
      - playlistapi
      - authenticationapi
      - highscoreapi
    environment:
      - NODE_ENV=development
    links:
      - randomizerapi
      - playlistapi
      - authenticationapi
      - highscoreapi

  componenttests:
    container_name: component_tests
    image: "bevrand/componenttests:${CIRCLE_SHA1}"
    depends_on:
    - randomizerapi
    - playlistapi
    - authenticationapi
    - proxyapi
    - highscoreapi
    - dataseeder
    links:
    - randomizerapi
    - playlistapi
    - authenticationapi
    - proxyapi
    - highscoreapi
    environment:
    - PYTHON_ENV=Test

  dataseeder:
    container_name: dataseeder
    image: "bevrand/dataseeder:${CIRCLE_SHA1}"
    depends_on:
       - dockermongo
       - dockergres
    links:
       - dockermongo
       - dockergres

  highscoreapi:
    container_name: highscoreapi
    image: "bevrand/highscoreapi:${CIRCLE_SHA1}"
    environment:
    - GO_ENV=docker
    - GIN_MODE=release
    depends_on:
    - redis
    links:
    - redis
    ports:
    - 4580:5000

  dockergres:
     container_name: dockergres
     image: "bevrand/dockergres:${CIRCLE_SHA1}"
     ports:
       - 5434:5432
     environment:
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_USER=postgres

  redis:
    container_name: redis
    image: redis
    ports: #6379
      - 6379:6379

  dockermongo:
    container_name: dockermongo
    image: mongo:3.6
    ports:
       - 27017:27017