definitions:
  models.ErrorModel:
    properties:
      errorMessage:
        type: string
      uniqueCode:
        type: string
    type: object
  models.PostObject:
    properties:
      drink:
        type: string
      playlist:
        type: string
      user:
        type: string
    type: object
  models.Score:
    properties:
      drink:
        type: string
      rolled:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/redis:
    post:
      consumes:
      - application/json
      description: Increase the scores
      operationId: post-high-scores
      parameters:
      - description: Up highscrore
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.PostObject'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorModel'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorModel'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorModel'
            type: object
      summary: Up or create a highscore
  /api/v1/redis/{user}/{playList}:
    get:
      consumes:
      - application/json
      description: get list by user and playlistnames
      operationId: get-high-scores
      parameters:
      - description: user
        in: path
        name: user
        required: true
        type: string
      - description: playlist
        in: path
        name: playList
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Score'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorModel'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorModel'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorModel'
            type: object
      summary: Show the high scores
  /ping:
    get:
      consumes:
      - application/json
      description: Is the api up?
      operationId: ping-pong
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Ping Pong
