# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
strategyType: Recreate
serviceAccountName:

image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "multivuerse"

podLabels: {}

config: {}
configRefs: []
secretRefs: []

ingress:
  enabled: true
  hosts:
    - host: bevrand
      paths: ['/']

livenessProbe:
  initialDelaySeconds: 30
readinessProbe:
  initialDelaySeconds: 10

resources: {}

service:
  port: 3000