# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
strategyType: Recreate

nameOverride: ""
fullnameOverride: ""

podLabels: {}

config: {}
configRefs: []
secretRefs: []

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

livenessProbe:
  initialDelaySeconds: 30
readinessProbe:
  initialDelaySeconds: 10

resources: {}

service:
  port: ""