- hosts: do
  remote_user: root
  gather_facts: False

  tasks:
  - name: Creates directory
    file: path=/root/docker state=directory
    register: changes_made

  - name: Set authorized key took from file
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/home/joerivrij/.ssh/id_rsa.pub') }}"

  - name: Upload first docker-compose for host
    copy: 
      src=../../docker-compose-created.yml
      dest=/root/docker
      mode=0644

  - command: "ls /root/docker"
    register: dir_out

  - debug: msg="{{ dir_out.stdout_lines }}"

  - name: remove possible old versions
    apt:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker-engine 
      - docker.io
    become: true
    when: changes_made.changed

  - name: install dependencies
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python-pip
    become: true
    when: changes_made.changed
 
  - name: install python modules (for older versions of OS)
    pip:
      name: "{{item}}"
      state: present
    with_items:
    - urllib3
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1
    when: changes_made.changed
    
     
  - name: Ubuntu add docker key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true
    when: changes_made.changed
     
  - name: create repo line
    command: bash -c "echo \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\" "
    register: docker_repo_line
    when: changes_made.changed
 
 
  - name: add docker repo
    apt_repository:
      repo: "{{ docker_repo_line.stdout }}"
      state: present
    become: true
    changed_when: False
    when: changes_made.changed
      
  - name: install docker ce
    apt:
      name: docker-ce
      state: present
    become: true
    when: changes_made.changed

  - name: Start Docker
    service: name=docker state=restarted

  - name: Installing docker compose
    pip:
      name: docker-compose
      state: present
    when: changes_made.changed

  - command: "docker-compose -f /root/docker/docker-compose-created.yml up -d"
    register: compose_up

  - debug: msg="{{ compose_up }}"